version: "3.8"
services:
  app:
    build: .
    container_name: pr-${PR_NUMBER}-backend
    environment:
      - PR_NUMBER=${PR_NUMBER}
    labels:
      - traefik.enable=true
      - traefik.http.routers.pr-${PR_NUMBER}.rule=Host(`pr-${PR_NUMBER}.localhost`)
      - traefik.http.services.pr-${PR_NUMBER}.loadbalancer.server.port=3000
    networks:
      - orchestrator-net
networks:
  orchestrator-net:
    external: true
    name: ephemeral-orchestrator_default
