version: "3.8"
services:
  backend:
    build: .
    container_name: ${DEPLOYMENT_ID}-backend
    environment:
      - DEPLOYMENT_ID=${DEPLOYMENT_ID}
      - FRONTEND_URL=http://${DEPLOYMENT_ID}.localhost
    labels:
      - traefik.enable=true
      - traefik.docker.network=ephemeral-orchestrator_default
      - traefik.http.routers.${DEPLOYMENT_ID}-api.rule=Host(`${DEPLOYMENT_ID}.localhost`)
      - traefik.http.services.${DEPLOYMENT_ID}-api.loadbalancer.server.port=3000
    networks:
      - orchestrator-net
networks:
  orchestrator-net:
    external: true
    name: ephemeral-orchestrator_default
